name: CD Fake
on: 
    workflow_dispatch:
        inputs:
            ambiente:
                type: choice
                options:
                    - homologacao
                    - producao
jobs:
    CI:
        runs-on: ubuntu-latest
        environment: ${{ inputs.ambiente }}
        steps:
            - name: Fake de deploy em ambiente
              run: echo "Deploy em ambiente de ${{ vars.AMBIENTE_DEPLOY }}"
